### ISSUE TITLE
Unable to determine graphics configuration on Windows / ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1

### ISSUE THREAD

**Issue by jzy3d** [jzy3d/jogl#12]
With JOGL 2.3.2, JOGL 2.4

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
        at jogamp.opengl.windows.wgl.awt.WindowsAWTWGLGraphicsConfigurationFactory.chooseGraphicsConfigurationImpl(WindowsAWTWGLGraphicsConfigurationFactory.java:171)
        at com.jogamp.nativewindow.GraphicsConfigurationFactory.chooseGraphicsConfiguration(GraphicsConfigurationFactory.java:424)
        at com.jogamp.opengl.awt.GLCanvas.chooseGraphicsConfiguration(GLCanvas.java:1513)
        at com.jogamp.opengl.awt.GLCanvas.addNotify(GLCanvas.java:609)
        at java.desktop/java.awt.Container.addImpl(Container.java:1150)
        at java.desktop/java.awt.Container.add(Container.java:1001)
```

Discussed 
on [JOGL forum](https://forum.jogamp.org/jogl-2-4-and-Java-17-Index-1-out-of-bounds-for-length-1-td4041575.html)
on [JOGL bugtracker](https://jogamp.org/bugzilla/show_bug.cgi?id=1317)
on [Jzy3D forum](https://groups.google.com/g/jzy3d/c/kPDXneumw-w)

**Comment by jzy3d** [comment]
As discussed on [JOGL bugtracker](https://jogamp.org/bugzilla/show_bug.cgi?id=1317), it can be workaround using the following VM options

```
--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED
```

**Comment by jzy3d** [comment]
What is surprising is that the 2.4 rc are supposed to contain a [fix commited on June 2020](https://github.com/jzy3d/jogl/commit/d335d99df25cc929d06765c3f1af3944f124f6a7) which exactly address this problem. 

Indeed, this bug is exactly the same that [the one that led to the fix](https://forum.jogamp.org/Crash-in-WindowsAWTWGLGraphicsConfigurationFactory-td4040703.html). This may mean (?) that the 2.4 build contains outdated jars.
